//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commnt_Id { get; set; }
        public string comment1 { get; set; }
        public int project_Id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public int author_Id { get; set; }
    }
}
