//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.meeting = new HashSet<meeting>();
            this.project = new HashSet<project>();
            this.project1 = new HashSet<project>();
        }
    
        public int person_id { get; set; }
        public string name_first { get; set; }
        public string name_last { get; set; }
        public int carrerpath_Id { get; set; }
    
        public virtual ICollection<meeting> meeting { get; set; }
        public virtual carrerpath carrerpath { get; set; }
        public virtual ICollection<project> project { get; set; }
        public virtual ICollection<project> project1 { get; set; }
    }
}
