//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.meeting = new HashSet<meeting>();
        }
    
        public int project_Id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int customer_Id { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public int buisness_manager { get; set; }
        public int project_manager { get; set; }
        public int site_Id { get; set; }
        public Nullable<int> adm_level { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual site site { get; set; }
        public virtual ICollection<meeting> meeting { get; set; }
        public virtual person businessManager { get; set; }
        public virtual person projectManager { get; set; }
    }
}
