//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.meeting = new HashSet<meeting>();
        }
    
        public int room_Id { get; set; }
        public string caption { get; set; }
        public int site_Id { get; set; }
    
        public virtual ICollection<meeting> meeting { get; set; }
        public virtual site site { get; set; }
    }
}
